### PR TITLE
Relax package dependency requirements

### PR DESCRIPTION
**Pull request by WeatherGod**
* Relax dependency requirements to allow newer versions.
* Gain numpy 2.x compatibility by fixing np.NaN to np.nan

### CODE REVIEW

**Comment by WeatherGod** [comment]
Closes #535. Trying it out without pinning numpy to <2.0 as, technically, it didn't before.

**Comment by WeatherGod** [comment]
Just did a numpy 2.0 compatibility check with ruff, and there are some mistakes that looks like are easily fixable.

**Comment by WeatherGod** [comment]
This also supersedes #536.

**Comment by monocongo** [comment]
Thanks for the tidy-up for numpy, @WeatherGod

**Pull request merged**
