### PR TITLE
Added Precipitation Concentration Index(PCI), issue #459 

### LINKED ISSUE #459: Addition of Precipitation Concentration Index
**Is your feature request related to a problem? Please describe.**
Precipitation Concentration Index or PCI  is an useful index to account the distribution of annual and seasonal rainfall amount. Even though the index itself is quite simple to implement it would be better to have a library which one may use when the need arises.

**Describe the solution you'd like**
I would like to contribute to this project by adding PCI as a function which was proposed by Oliver (1980) and further modified by De Luis et al. (2011) to give Seasonal PCI or SPCI.
Link for Oliver(1980): https://doi.org/10.1111/j.0033-0124.1980.00300.x
Link for De Luis et al. (2011): https://doi.org/10.5194/nhess-11-1259-2011

**Additional context**
Kindly let me know if this is in line with the aim of the project and if I may submit a PR.

### PR DESCRIPTION
**Pull request by oshin94**
@monocongo I have added the feature for PCI and the necessary test cases to the best of my capabilities in the indices.py file and test_indices.py file respectively. Please have a look. Will be updating the doc files and other minor changes in another update.

### CODE REVIEW

**Comment by oshin94** [comment]
@monocongo there are some unnecessary else/elif after return and other issues in the indices.py file for which the analysis is failing repeatedly. I have not made any changes in those blocks and seems like the issue was present from before. kindly advise, what is the best step to be taken.

**Comment by monocongo** [comment]
It seems that we're missing a `rain_mm` fixture causing the PCI test case to fail. For that, I think we need to come up with a `rain_mm` numpy dataset, write it to a corresponding `.npy` file, then reference that file in [`tests/conftest.py`](https://github.com/monocongo/climate_indices/blob/master/tests/conftest.py) as is done for some of the other fixtures we use for pytest.

**Comment by monocongo** [comment]
Excellent progress @oshin94, thank you!

Now only a single error is showing up for the PCI tests:
```
FAILED tests/test_indices.py::test_pci - ValueError: NaN values in time-series...
```

**Comment by oshin94** [comment]
@monocongo I hope the test failure has been fixed. Please provide the approval for the workflow and see if the branch can be merged with master.

**Pull request merged**
