### PR TITLE
Can't assume that the input's coordinates are in the same order as the output's dimensions

### LINKED ISSUE #445: Getting error: conflicting sizes for dimension 'lat' for SPI calculation from NetCDF
**[How to craft a useful, minimal bug report](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)**

**Describe the bug**
I'm trying to calculate SPI from Chirps data in NetCDF format and I'm getting 

"ValueError: conflicting sizes for dimension 'lat': length 12 on the data but length 170 on coordinate 'lat'" error from XArray. I've been using the 1.0.9 version, but also tried the 1.0.8 and 1.0.7 versions with the same error. 

Any ideas to solve the issue?

**To Reproduce**
I'm trying to create SPI with the following command :

spi_chirps_2021_v2 % spi --periodicity monthly --scales 12 --calibration_start_year 1981 --calibration_end_year 2020 --netcdf_precip /_temp/spi_chirps_2021_v2/input_nc/tr_clip_chirps_1months_1980_2021.nc --var_name_precip precip --output_file_base /_temp/spi_chirps_2021_v2/output_nc/tr_chirps --multiprocessing all --save_params /_temp/spi_chirps_2021_v2/Fitting/tr_chirps_fitting.nc --overwrite

**Desktop (please complete the following information):**
- OS: MacOS X 10.15.7
- Python Version : 3.7.11

### PR DESCRIPTION
**Pull request by WeatherGod**
* Closes #445

### CODE REVIEW

**Comment by WeatherGod** [comment]
Note, I think this bug also is sort-of present in `__main__.py`, but it is hard to be sure. It makes some slightly different assumptions and it might all be ok when it comes out in the wash. I have generated SPI values using this patch on my own datasets through the `spi` command, and I have generated SPEI values using the same datasets through the `process_climate_indices` command without issues that I have noticed so far.

**Comment by WeatherGod** [comment]
Failures noted by DeepSource are unrelated to this PR.

**Comment by monocongo** [comment]
The failing tests are not caused by this PR. The tests went off the rails a while back and I've not had time to right the ship, another user has identified the possible cause, see #419.

**Comment by monocongo** [comment]
What's the best way forward? My thinking is that it's putting the cart before the horse to approve PRs with failing tests, but fixing the tests might be a long/laborious process (one reason I've procrastinated) and I don't want to hold up good PRs on account of it.

**Comment by WeatherGod** [comment]
Well, I have some good news for you. I just took a look at one of the test failures, and I figured out what is happening and I think I know the correct thing to do. I'll submit the PR for that and let you mull it over as you have better historical context for the relevant chunk of code (looks like the code got moved around, so the history is difficult to figure out). I'll look at the other one next and see if I can figure it out, too.

**Comment by monocongo** [comment]
That is such good news and totally appreciated. Once the tests are working as expected again then reviewing/approving all of the outstanding PRs will be easier.

**Comment by WeatherGod** [comment]
Rebased and force-pushed to include the recent fixes.

**Pull request merged**
